CREATE TABLE IF NOT EXISTS student_timetable_reports (
    ReportID INT AUTO_INCREMENT PRIMARY KEY,
    StudentID INT NOT NULL,
    SemesterID INT NOT NULL,
    ProgramID INT NOT NULL,
    CourseID INT NOT NULL,
    FacultyID INT NOT NULL,
    DayOfWeek VARCHAR(20) NOT NULL,
    SlotID INT NOT NULL,
    RoomID INT NOT NULL,
    CourseName VARCHAR(255) NOT NULL,
    FacultyName VARCHAR(255) NOT NULL,
    RoomNumber VARCHAR(50) NOT NULL,
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (StudentID) REFERENCES students(StudentID),
    FOREIGN KEY (SemesterID) REFERENCES semesters(SemesterID),
    FOREIGN KEY (ProgramID) REFERENCES offered_programs(ProgramID),
    FOREIGN KEY (CourseID) REFERENCES courses(CourseID),
    FOREIGN KEY (FacultyID) REFERENCES faculty(FacultyID),
    FOREIGN KEY (SlotID) REFERENCES time_slots(SlotID),
    FOREIGN KEY (RoomID) REFERENCES rooms(RoomID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
